[project]
name = "dataextraction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "pyautogui>=0.9.54",
    "pydantic>=2.12.5",
    "pyinstaller>=6.17.0",
    "python-dotenv>=1.2.1",
]
